#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"

GH_API=https://api.github.com/repos/opencart/opencart/releases/latest
VERSION=$(curl -s $GH_API | grep -oP '"tag_name": "\K(.*)(?=")')

URL="https://github.com/opencart/opencart/releases/download/$VERSION/opencart-$VERSION.zip"

dl $URL $SRC
