#!/bin/sh -ex
echo "do nothing - core requires no post-package configuration commands"

DB_NAME=opencart
DB_USER=opencart
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/opencart

tar -xf $SRC/master.tar.gz -C $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/opencart-master/upload $WEBROOT


cd $WEBROOT
rm -r /var/www/opencart-master
mv $WEBROOT/config-dist.php $WEBROOT/config.php
mv $WEBROOT/admin/config-dist.php $WEBROOT/admin/config.php

a2dissite 000-default
a2ensite opencart

/etc/init.d/mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'"

chown www-data:www-data /var/www/opencart -R
cd $WEBROOT/install
php cli_install.php install --db_hostname localhost --db_username $DB_USER --db_port 3306 --db_database $DB_NAME --db_driver mysqli --db_password $DB_PASS --username admin --password turnkey --email admin@example.com --http_server TURNKEY_DOMAIN/
rm -r $WEBROOT/install
mv $WEBROOT/system/storage /var/www/storage
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '/var/www/storage/'|" $WEBROOT/config.php
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '/var/www/storage/'|" $WEBROOT/admin/config.php



/etc/init.d/mysql stop
