#!/bin/sh -ex

DB_NAME=opencart
DB_USER=opencart
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/opencart
STORAGE=$(dirname $WEBROOT)/opencart-storage

DOMAIN=www.example.com

unzip $SRC/opencart-*.zip -d $SRC/opencart
mv $SRC/opencart/upload $WEBROOT
rm -r $SRC/opencart*

cd $WEBROOT
mv $WEBROOT/config-dist.php $WEBROOT/config.php
mv $WEBROOT/admin/config-dist.php $WEBROOT/admin/config.php

a2dissite 000-default
a2ensite opencart
a2enmod rewrite

service mysql start

MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'"

cd $WEBROOT/install
php cli_install.php install --db_hostname localhost --db_username $DB_USER --db_port 3306 --db_database $DB_NAME --db_driver mysqli --db_password $DB_PASS --username admin --password turnkey --email admin@example.com --http_server $DOMAIN/
rm -r $WEBROOT/install
mv $WEBROOT/system/storage $STORAGE
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '$STORAGE/'|" $WEBROOT/config.php
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '$STORAGE/'|" $WEBROOT/admin/config.php

service mysql stop

LOCATIONS="$STORAGE/cache/ $STORAGE/download/ $STORAGE/logs/
    $STORAGE/modification/ $STORAGE/session/ $STORAGE/upload/
    $STORAGE/vendor/ $WEBROOT/image/ $WEBROOT/image/cache/
    $WEBROOT/image/catalog/ $WEBROOT/config.php $WEBROOT/admin/config.php
    $WEBROOT/catalog/"

for location in $LOCATIONS; do
    chown -R www-data:www-data $location
done
